name: Python Package using Conda

on: [push, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda config --add channels defaults
        conda config --add channels bioconda
        conda config --add channels conda-forge
        conda install -y --file requirements.txt
    - name: Lint with flake8 (currently disabled)
      run: |
        # conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build
      run: |
        make
    - name: Run test dataset
      run: |
        mkdir build_test
        cd build_test
        python ../string_decomposer.py ../test_data/read.fa ../test_data/DXZ1_star_monomers.fa
    - name: Archive run results
      uses: actions/upload-artifact@v2
      with:
        name: final_decomposition.tsv
        path: build_test/final_decomposition.tsv
    
